parallel-jobs = 1
strict-sigcheck = false
brand = "morphe"

[Reddit]
pkg-name = "com.reddit.frontpage"
badge-color = "FF4500"
badge-icon = "reddit"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/reddit/com.reddit.frontpage"
patcher-args = "-e 'Custom branding name for Reddit' -OappName='Reddit'"

[Reddit.patches]
"github:MorpheApp/morphe-patches" = []

[Twitter]
pkg-name = "com.twitter.android"
badge-color = "000000"
badge-icon = "x"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/x/com.twitter.android"

[Twitter.patches]
"github:crimera/piko" = []


[Instagram]
pkg-name = "com.instagram.android"
badge-color = "FF0069"
badge-icon = "instagram"
version = "latest"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/instagram/com.instagram.android"
github-dlurl = "https://github.com/softpyscho/apkforge/releases/tag/com.instagram.android"

[Instagram.patches]
"github:crimera/piko" = { version = "dev" }

[WARP]
pkg-name = "com.cloudflare.onedotonedotonedotone"
badge-color = "F48120"
badge-icon = "cloudflare"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/1-1-1-1-warp/com.cloudflare.onedotonedotonedotone"

[WARP.patches]
"github:rushiranpise/morphe-patches" = []

[Splitwise]
pkg-name = "com.Splitwise.SplitwiseMobile"
badge-color = "40B89C"
badge-icon = "splitwise"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/splitwise/splitwise/"
uptodown-dlurl = "https://splitwise.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/splitwise/com.Splitwise.SplitwiseMobile"

[Splitwise.patches]
"github:rushiranpise/morphe-patches" = []

[Truecaller]
pkg-name = "com.truecaller"
badge-color = "0080FF"
badge-icon = "truecaller"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/truecaller/com.truecaller"

[Truecaller.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Xodo]
pkg-name = "com.xodo.pdf.reader"
badge-color = "0078D4"
badge-icon = "adobeacrobatreader"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/apryse-software-inc/xodo-pdf-reader-editor"
uptodown-dlurl = "https://xodo-docs.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/xodo-pdf-reader/com.xodo.pdf.reader"

[Xodo.patches]
"github:hoo-dles/morphe-patches" = []

[Amazon-Prime-Video]
pkg-name = "com.amazon.avod.thirdpartyclient"
badge-color = "00A8E1"
badge-icon = "amazonprimevideo"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/amazon-prime-video/com.amazon.avod.thirdpartyclient"

[Amazon-Prime-Video.patches]
"github:hoo-dles/morphe-patches" = []

[TickTick]
pkg-name = "com.ticktick.task"
badge-color = "4772FA"
badge-icon = "ticktick"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/ticktick/com.ticktick.task"

[TickTick.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Greenify]
pkg-name = "com.oasisfeng.greenify"
badge-color = "43A047"
badge-icon = "android"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/oasisfeng/greenify"
uptodown-dlurl = "https://greenify.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/greenify/com.oasisfeng.greenify"
github-dlurl = "https://github.com/softpyscho/apkforge/releases/tag/com.oasisfeng.greenify"

[Greenify.patches]
"github:rushiranpise/morphe-patches" = []

[Battery-Guru]
pkg-name = "com.paget96.batteryguru"
badge-color = "4CAF50"
badge-icon = "battery_charging_full"
version = "latest"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/paget96/battery-guru/"
uptodown-dlurl = "https://battery-guru.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/battery-guru-battery-health/com.paget96.batteryguru"

[Battery-Guru.patches]
"github:arandomhooman/hoomans-morphe-patches" = { version = "dev" }

[Bitget]
app-name = "Bitget"
mirror = true
version = "latest"
arch = "arm64-v8a"
pkg-name = "com.bitget.exchange"          # ← added
apkmirror-dlurl = "https://www.apkmirror.com/apk/bg-limited/bitget-buy-sell-crypto/"
uptodown-dlurl = "https://bitget.en.uptodown.com/android"
apkpure-dlurl   = "https://apkpure.com/bitget/com.bitget.exchange"

[Mixplorer]
app-name = "Mixplorer"
mirror = true
version = "latest"
arch = "arm64-v8a"
pkg-name = "com.mixplorer"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hootan-parsa/mixplorer-hootanparsa/"
uptodown-dlurl = "https://mixplorer.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/mixplorer/com.mixplorer"

[Mix-Archive]
app-name = "Mix Archive"
mirror = true
version = "latest"
arch = "arm64-v8a"
pkg-name = "com.mixplorer.addon.archive"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hootan-parsa/mix-archive/"
uptodown-dlurl = "https://mix-archive.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/mix-archive/com.mixplorer.addon.archive"

[Stremio]
app-name = "Stremio"
mirror = true
version = "latest"
arch = "arm64-v8a"
pkg-name = "com.stremio.one"
direct-dlurl = "https://www.stremio.com/downloads"
apkmirror-dlurl = "https://www.apkmirror.com/apk/stremio/stremio-2/"
uptodown-dlurl = "https://stremio-one.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/stremio-app/com.stremio.one"

[RedotPay]
app-name = "RedotPay"
mirror = true
version = "latest"
arch = "arm64-v8a"
pkg-name = "com.redotpay"
direct-dlurl = "https://www.redotpay.com/app-download"
uptodown-dlurl = "https://redotpay.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/redotpay-wallet-buy-btc/com.redotpay"

[Duck-Detector]
app-name = "Duck Detector"
mirror = true
keep-filename = true
version = "nightly"
arch = "all"
pkg-name = "Duck.Detector"
github-dlurl = "https://github.com/eltavine/Duck-Detector-Refactoring/releases/tag/nightly"

[WhatsApp]
app-name = "WhatsApp"
mirror = true
version = "2.26.30.xx"
arch = "arm64-v8a"
pkg-name = "com.whatsapp"
apkmirror-dlurl = "https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/"
uptodown-dlurl = "https://whatsapp-messenger.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/whatsapp-messenger/com.whatsapp"
[WhatsApp-Business]
app-name = "WhatsApp Business"
mirror = true
version = "2.26.30.xx"
arch = "arm64-v8a"
pkg-name = "com.whatsapp.w4b"
apkmirror-dlurl = "https://www.apkmirror.com/apk/whatsapp-inc/whatsapp-business/"
uptodown-dlurl = "https://whatsapp-business.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/whatsapp-business/com.whatsapp.w4b"