# ---------------------------------------------------------
# Copyright (C) 2026 softpyscho
# 
# DO NOT REMOVE OR ALTER THIS COPYRIGHT HEADER.
# This file is part of apkforge.
# Canonical source: https://github.com/softpyscho/apkforge
#
# Licensed under the GNU GPLv3. You may modify this file,
# but you MUST keep this original copyright notice intact
# and prominently state any changes made.
# See the AUTHORS file in the root directory for details.
# ---------------------------------------------------------

"""
Generates the dynamic app listing section of README.md from config.toml.

Usage:
    uv run python -m src.scripts.readme

Reads config.toml, groups apps by patch source, and replaces the content
between <!-- APPS_START --> and <!-- APPS_END --> markers in README.md.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.parse
from collections import OrderedDict
from pathlib import Path

from src.core.config import CONFIG_PATH, load_toml, parse_app_entries, parse_config


def _source_url(source: str) -> str:
    """Convert a patch source string like 'github:user/repo' to a full URL."""
    scheme, path = source.split(":", 1)
    if scheme == "github":
        return f"https://github.com/{path}"
    elif scheme == "gitlab":
        return f"https://gitlab.com/{path}"
    return path


def _source_label(source: str) -> str:
    """Extract 'user/repo' from 'github:user/repo'."""
    return source.split(":", 1)[1]


def _source_platform(source: str) -> str:
    """Return 'github' or 'gitlab'."""
    return source.split(":", 1)[0]


def _badge_name(source: str) -> str:
    """Generate a human-readable badge name from a source like 'github:crimera/piko'."""
    label = _source_label(source)
    parts = label.split("/")
    # Use "Author / Repo" for clarity, e.g. "Crimera / Piko"
    if len(parts) > 1:
        author = parts[0].replace("-", " ").title()
        repo = parts[1].replace("-", " ").title()
        return f"{author} / {repo}"
    return parts[0].replace("-", " ").title()


def _version_label(entry, versions_cache: dict[str, str]) -> str:
    """Generate a human-readable version strategy label."""
    color = entry.badge_color or "3e9cfb"
    if entry.version in ("auto", "latest"):
        v = versions_cache.get(entry.table)
        if v:
            encoded_v = urllib.parse.quote(f"v{v}" if not v.startswith("v") else v, safe="")
            return f'![version](https://img.shields.io/badge/version-{encoded_v}-{color}?logo=android&logoColor=white)'
            
    if entry.version == "auto":
        return f'![version](https://img.shields.io/badge/version-Auto-{color}?logo=android&logoColor=white)'
    elif entry.version == "latest":
        # Check if any patch spec uses dev version
        label = "Latest"
        for spec in entry.patches.values():
            if isinstance(spec, dict) and spec.get("version") == "dev":
                label = "Latest (dev)"
                break
        encoded_v = urllib.parse.quote(label, safe="")
        return f'![version](https://img.shields.io/badge/version-{encoded_v}-{color}?logo=android&logoColor=white)'
    else:
        encoded_v = urllib.parse.quote(f"v{entry.version}" if not entry.version.startswith("v") else entry.version, safe="")
        return f'![version](https://img.shields.io/badge/version-{encoded_v}-{color}?logo=android&logoColor=white)'


def _load_versions_cache() -> dict[str, str]:
    """Load the versions info cache generated by the build process."""
    cache_path = Path("versions_info.json")
    versions = {}
    if cache_path.exists():
        try:
            data = json.loads(cache_path.read_text(encoding="utf-8"))
            for item in data.get("success", []):
                if "app" in item and "version" in item:
                    versions[item["app"]] = item["version"]
        except (json.JSONDecodeError, OSError):
            pass
    return versions

def _load_patches_cache() -> dict[str, list[str]]:
    """Load the patches info cache generated by the build process."""
    cache_path = Path("patches_info.json")
    if cache_path.exists():
        try:
            return json.loads(cache_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def _patches_label(entry, patches_cache: dict[str, list[str]], general_patches: set[str] = None) -> str:
    """Describe which patches are applied."""
    all_includes = []
    all_excludes = []

    for spec in entry.patches.values():
        all_includes.extend(spec.get("include", []))
        all_excludes.extend(spec.get("exclude", []))

    if entry.patcher_args:
        enabled = re.findall(r"-e\s+'([^']+)'", " ".join(entry.patcher_args))
        disabled = re.findall(r"-d\s+'([^']+)'", " ".join(entry.patcher_args))
        all_includes.extend(enabled)
        all_excludes.extend(disabled)

    applied = set()
    has_cache = entry.table in patches_cache and patches_cache[entry.table]

    if has_cache:
        if not entry.exclusive_patches:
            applied.update(patches_cache[entry.table])
        applied.update(all_includes)
        applied.difference_update(all_excludes)
    elif entry.exclusive_patches and all_includes:
        applied.update(all_includes)
        applied.difference_update(all_excludes)

    if general_patches:
        to_remove = general_patches - set(all_includes)
        applied_specific = applied - to_remove
        if applied_specific:
            applied = applied_specific

    options_str = ""
    if entry.patcher_args:
        options = re.findall(r"-O(\w+)='([^']+)'", " ".join(entry.patcher_args))
        if options:
            options_str = "<br>⚙️ " + ", ".join(f"{k}={v}" for k, v in options)

    if has_cache or (entry.exclusive_patches and all_includes):
        sorted_patches = sorted(applied, key=lambda x: x.lower())
        patch_list = "<br>".join(f"`{p}`" for p in sorted_patches)
        summary = f"<summary><b>{len(sorted_patches)} patches</b></summary>"
        result = f"<details>{summary}{patch_list}{options_str}</details>"
    else:
        result = f"*(Pending cache update)*{options_str}"

    return result


def _app_badge(entry) -> str:
    """Generate a clean shield badge for the app linking to Play Store."""
    name = entry.app_name if entry.app_name != entry.table.replace("-", " ") else entry.table.replace("-", " ")
    encoded_name = urllib.parse.quote(name.replace("-", "--"), safe="")
    badge_url = f"https://img.shields.io/badge/{encoded_name}-{entry.badge_color}?style=flat-square&logo={entry.badge_icon}&logoColor=%23FFFFFF"
    
    if entry.pkg_name:
        return f"[![{name}]({badge_url})](https://play.google.com/store/apps/details?id={entry.pkg_name})"
    return f"![{name}]({badge_url})"


def _obtainium_link(entry) -> str:
    """Generate an Obtainium deep link for this specific app."""
    name = entry.app_name if entry.app_name != entry.table.replace("-", " ") else entry.table.replace("-", " ")
    obtainium_name = f"{name} {entry.brand.title()}"
    
    base_name = f"{entry.app_name.lower().replace(' ', '-')}-{entry.brand.lower().replace(' ', '-')}"
    apk_filter = f"^{base_name}-(v\\w*\\d|\\d|vbuild).*\\.apk$"
    
    settings = {
        "apkFilterRegEx": apk_filter
    }
    
    payload = {
        "id": entry.pkg_name or f"com.{entry.table.lower()}.app",
        "name": obtainium_name,
        "author": "softpyscho",
        "url": "https://github.com/softpyscho/apkforge",
        "additionalSettings": json.dumps(settings, separators=(',', ':'))
    }
    
    raw_uri = f"obtainium://app/{json.dumps(payload, separators=(',', ':'))}"
    encoded_uri = urllib.parse.quote(raw_uri, safe="()*")
    
    deep_link = f"https://apps.obtainium.imranr.dev/redirect?r={encoded_uri}"
    badge_img = f'![Add to Obtainium](https://img.shields.io/badge/Add_to_Obtainium-8b5cf6?style=flat-square&logo=android&logoColor=white)'
    return f"[{badge_img}]({deep_link})"


def generate_apps_section() -> str:
    """Generate the apps section markdown table."""
    data = load_toml(CONFIG_PATH)
    config = parse_config(data)
    entries = parse_app_entries(data, config)

    patches_cache = _load_patches_cache()
    versions_cache = _load_versions_cache()

    # Group entries by patch source (ordered by first appearance)
    groups: OrderedDict[str, list] = OrderedDict()
    for entry in entries:
        if not entry.enabled:
            continue
        for source in entry.patches:
            if source not in groups:
                groups[source] = []
            # Avoid duplicating an app if it appears under only one source
            if not any(e.table == entry.table for e in groups[source]):
                groups[source].append(entry)

    # Compute general patches per source
    source_general_patches = {}
    for source, apps in groups.items():
        if len(apps) > 1:
            sets = []
            for app in apps:
                if app.table in patches_cache:
                    sets.append(set(patches_cache[app.table]))
            if len(sets) > 1:
                source_general_patches[source] = set.intersection(*sets)
            else:
                source_general_patches[source] = set()
        else:
            source_general_patches[source] = set()

    lines: list[str] = []

    for source, apps in groups.items():
        platform = _source_platform(source)
        label = _source_label(source)
        url = _source_url(source)
        badge = _badge_name(source)
        platform_badge = "gitlab" if platform == "gitlab" else "github"

        # Section header with badge
        encoded_badge = urllib.parse.quote(badge, safe="")
        lines.append(f'### <img src="https://img.shields.io/badge/{encoded_badge}-4500FF?style=for-the-badge&logo={platform_badge}&logoColor=white" alt="{badge}">')
        lines.append("")
        if platform == "gitlab":
            lines.append(f"> **Source:** [`{label}`]({url}) (GitLab)")
        else:
            lines.append(f"> **Source:** [`{label}`]({url})")
        lines.append("")

        lines.append("<div align=\"center\">")
        lines.append("")
        lines.append("| App | Arch | Version | Patches | Obtainium |")
        lines.append("|:---|:----:|:-------:|:--------|:---------:|")

        for entry in apps:
            badge = _app_badge(entry)
            arch = f"`{entry.arch}`"
            version = _version_label(entry, versions_cache)
            
            general_patches = source_general_patches.get(source, set())
            patches = _patches_label(entry, patches_cache, general_patches)
            obtainium = _obtainium_link(entry)

            lines.append(f"| {badge} | {arch} | {version} | {patches} | {obtainium} |")

        lines.append("")
        lines.append("</div>")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Remove trailing separator
    if lines and lines[-2] == "---":
        lines.pop(-1)
        lines.pop(-1)

    return "\n".join(lines)


def update_readme() -> bool:
    """Update README.md with the generated apps section. Returns True if changed."""
    readme_path = Path("README.md")
    if not readme_path.exists():
        print("README.md not found", file=sys.stderr)
        return False

    content = readme_path.read_text(encoding="utf-8")

    start_marker = "<!-- APPS_START -->"
    end_marker = "<!-- APPS_END -->"

    if start_marker not in content or end_marker not in content:
        print(f"Markers {start_marker} / {end_marker} not found in README.md", file=sys.stderr)
        return False

    apps_section = generate_apps_section()
    new_block = f"{start_marker}\n\n{apps_section}\n\n{end_marker}"

    # Replace everything between (and including) the markers
    pattern = re.compile(
        re.escape(start_marker) + r".*?" + re.escape(end_marker),
        re.DOTALL
    )
    new_content = pattern.sub(new_block, content)

    if new_content == content:
        print("README.md is already up to date.")
        return False

    readme_path.write_text(new_content, encoding="utf-8")
    print("README.md updated successfully.")
    return True


def main() -> None:
    match sys.argv[1:]:
        case ["generate"]:
            print(generate_apps_section())
        case ["update"]:
            update_readme()
        case _:
            update_readme()


if __name__ == "__main__":
    main()
